version: "3.7"

services:
    api_flask:
        build:
          context: /home/kali/Desktop/api/
        ports:
          - "5000"

    nginx:
        build: ./nginx
        depends_on:
          - api_flask
        ports:
          - "80:80"